variables:
  ArtifactPath: '\\nofresbld002\tfsdrops\$(Build.SourceBranchName)_$(Build.DefinitionName)\$(Build.BuildNumber)'

trigger: none

# NOTE! in UTC !!!
schedules:
- cron: "0 2 * * *"
  #always: true
  displayName: Daily build master
  branches:
    include:
    - master

resources:
  repositories:
  - repository: opcau-datasource # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: srclosson/grafana-opcua-datasource
    ref: prediktor-opc-ae

pool:
  name: apis-foundation-master

steps:
- checkout: self
- checkout: opcau-datasource
- task: NuGetCommand@2
  displayName: 'NuGet restore grafana-setup.sln'
  inputs:
    restoreSolution: 'grafana-setup/grafana-setup.sln'


- task: VSBuild@1
  displayName: 'Build solution grafana-setup.sln'
  inputs:
    solution: 'Grafana-UA-Panel/grafana-setup/grafana-setup.sln'

    platform: 'Any CPU'

    configuration: Setup_Release

    createLogFile: true

  timeoutInMinutes: 60

