variables:
  ArtifactPath: '\\nofresbld002\tfsdrops\$(Build.SourceBranchName)_$(Build.DefinitionName)\$(Build.BuildNumber)'

trigger: none

# NOTE! in UTC !!!
schedules:
- cron: "0 2 * * *"
  #always: true
  displayName: Daily build master
  branches:
    include:
    - master

resources:
  repositories:
  - repository: opcau-datasource # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: srclosson/grafana-opcua-datasource
    ref: prediktor-opc-ae

pool:
  name: apis-foundation-master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.5'
- script: yarn install
  workingDirectory: 'Grafana-UA-Panel/grafana-ua-panel'


- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0' #From SWA with love!

- checkout: self
- checkout: opcau-datasource
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DevEnvBuild@2
  inputs:
    solution: 'Grafana-UA-Panel/grafana-setup/grafana-setup.sln'
    vsVersion: 'latest'


  timeoutInMinutes: 60

