variables:
  ArtifactPath: '\\nofresbld002\tfsdrops\$(Build.SourceBranchName)_$(Build.DefinitionName)\$(Build.BuildNumber)'

trigger: none

# NOTE! in UTC !!!
schedules:
- cron: "0 2 * * *"
  #always: true
  displayName: Daily build master
  branches:
    include:
    - master

resources:
  repositories:
  - repository: opcau-datasource # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: srclosson/grafana-opcua-datasource
    ref: prediktor-opc-ae

pool:
  name: apis-foundation-master

steps:
- checkout: self
- checkout: opcau-datasource
- task: NodeTool@0
  inputs:
    versionSpec: '14.5'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

#grafana-ua-panel
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/grafana-ua-panel'
   arguments: install
  displayName: 'grafana-ua-panel install pkgs'

- task: Yarn@3
  displayName: 'grafana-ua-panel build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/grafana-ua-panel'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy grafana-ua-panel'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/grafana-ua-panel/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/grafana-ua-panel'
#ua-dashboard
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/ua-dashboard'
   arguments: install
  displayName: 'ua-dashboard install pkgs'

- task: Yarn@3
  displayName: 'ua-dashboard build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/ua-dashboard'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy ua-dashboard'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/ua-dashboard/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/ua-dashboard'
#ua-list-view
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/ua-list-view'
   arguments: install
  displayName: 'ua-list-view install pkgs'

- task: Yarn@3
  displayName: 'ua-list-view build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/ua-list-view'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy ua-list-view'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/ua-list-view/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/ua-list-view'
#opcua
- task: Yarn@3
  inputs:
   ProjectDirectory: 'grafana-opcua-datasource'
   arguments: install
  displayName: 'grafana-opcua-datasource install pkgs'

- task: Yarn@3
  displayName: 'grafana-opcua-datasource build'
  inputs:
   projectDirectory: 'grafana-opcua-datasource'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy grafana-opcua-datasource'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/grafana-opcua-datasource/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/opcua'

- task: PublishPipelineArtifact@1
  displayName: Publish the artifact
  inputs:
    path: '$(build.artifactstagingdirectory)'
    artifact: '$(Build.Repository.Name)'

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0' #From SWA with love!


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DevEnvBuild@2
  inputs:
    solution: 'Grafana-UA-Panel/grafana-setup/grafana-setup.sln'
    vsVersion: 'latest'


  timeoutInMinutes: 60

