variables:
  ArtifactPath: '\\nofresbld002\tfsdrops\$(Build.SourceBranchName)_$(Build.DefinitionName)\$(Build.BuildNumber)'

trigger: none

# NOTE! in UTC !!!
schedules:
- cron: "0 2 * * *"
  #always: true
  displayName: Daily build master
  branches:
    include:
    - master

resources:
  repositories:
  - repository: opcau-datasource # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: srclosson/grafana-opcua-datasource
    ref: prediktor-opc-ae

pool:
  name: apis-foundation-master

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0' #From SWA with love!

- checkout: self
- checkout: opcau-datasource
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    workingDirectory: 'Grafana-UA-Panel/grafana-setup/''


- task: VSBuild@1
  displayName: 'Build solution grafana-setup.sln'
  inputs:
    solution: 'Grafana-UA-Panel/grafana-setup/grafana-setup.sln'

    platform: 'Any CPU'

    configuration: Release

    createLogFile: true

  timeoutInMinutes: 60

