variables:
  ArtifactPath: '\\nofresbld002\tfsdrops\$(Build.SourceBranchName)_$(Build.DefinitionName)\$(Build.BuildNumber)'

trigger: none

# NOTE! in UTC !!!
schedules:
- cron: "0 4 * * *"
  #always: true
  displayName: Daily build master
  branches:
    include:
    - master

resources:
  repositories:
  - repository: opcau-datasource # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: srclosson/grafana-opcua-datasource
    ref: prediktor-opc-ae
  - repository: grafanaplugins # The name used to reference this repository in the checkout step
    type: github
    endpoint: cfjeld
    name: PrediktorAS/grafana
    ref: main

pool:
  name: apis-foundation-master 
  #nofresbld002

steps:
- checkout: grafanaplugins
- checkout: opcau-datasource
- task: NodeTool@0
  inputs:
    versionSpec: '14.5'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'

#grafana-ua-panel
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/grafana-ua-panel'
   arguments: install
  displayName: 'grafana-ua-panel install pkgs'

- task: Yarn@3
  displayName: 'grafana-ua-panel build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/grafana-ua-panel'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy grafana-ua-panel'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/grafana-ua-panel/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/grafana-ua-panel'
#ua-dashboard
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/ua-dashboard'
   arguments: install
  displayName: 'ua-dashboard install pkgs'

- task: Yarn@3
  displayName: 'ua-dashboard build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/ua-dashboard'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy ua-dashboard'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/ua-dashboard/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/ua-dashboard'
#ua-list-view
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/ua-list-view'
   arguments: install
  displayName: 'ua-list-view install pkgs'

- task: Yarn@3
  displayName: 'ua-list-view build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/ua-list-view'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy ua-list-view'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/ua-list-view/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/ua-list-view'

#ua-event-view
- task: Yarn@3
  inputs:
   ProjectDirectory: 'Grafana-UA-Panel/ua-event-view'
   arguments: install
  displayName: 'ua-event-view install pkgs'

- task: Yarn@3
  displayName: 'ua-event-view build'
  inputs:
   projectDirectory: 'Grafana-UA-Panel/ua-event-view'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy ua-event-view'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/ua-event-view/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/ua-event-view'
#opcua
- task: Yarn@3
  inputs:
   ProjectDirectory: 'grafana-opcua-datasource'
   arguments: install
  displayName: 'grafana-opcua-datasource install pkgs'

- task: Yarn@3
  displayName: 'grafana-opcua-datasource build'
  inputs:
   projectDirectory: 'grafana-opcua-datasource'
   arguments: 'build'
  
- task: CopyFiles@2
  displayName: 'Copy grafana-opcua-datasource'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/grafana-opcua-datasource/dist'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/opcua'


- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.8.0' #From SWA with love!


- task: DotNetCoreCLI@2
  displayName: 'Restore vs solutions'
  inputs:
    command: restore
    projects: '**/*.csproj'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'publish'
#     projects: 'grafana-opcua-datasource/pkg/dotnet/plugin-dotnet/plugin-dotnet.sln'

# - task: MSBuild@1
#   displayName: 'Build backend plugin'
#   inputs:
#     solution: 'grafana-opcua-datasource/pkg/dotnet/plugin-dotnet/plugin-dotnet.sln'
#     platform: 'Any CPU'
#     configuration: 'Release'

- task: CopyFiles@2
  displayName: 'Copy setupkit'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/grafana-opcua-datasource/pkg/dotnet/plugin-dotnet/bin/Release/netcoreapp3.1/publish'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/binaries/opcua'

- task: DevEnvBuild@2
  displayName: 'Build setupkit'
  inputs:
    solution: 'Grafana-UA-Panel/grafana-setup/grafana-setup.sln'
    vsVersion: 'latest'
    buildCfg: 'Release'
    buildPlatform: 'Any CPU'

- task: CopyFiles@2
  displayName: 'Copy setupkit'
  inputs:
    SourceFolder: '$(agent.builddirectory)/s/Grafana-UA-Panel/grafana-setup/grafana-setup/Release'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/setup'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'grafana'
    publishLocation: 'FilePath'
    TargetPath: $(ArtifactPath)

  timeoutInMinutes: 60

